### ISSUE TITLE
(Accordion) Render content on header click

### ISSUE THREAD

**Issue by alexstoyanov** [oblador/react-native-collapsible#145]
My use case is that I have to render a lot of data from the server. That said - is there an option to load the data on demand - i.e. to render the headers in the Accordion and when the user clicks on one header to load data from server for that specific header. Something like onHeaderClicked method:

                       <Accordion
                            sections={sections}
                            renderHeader={this._renderHeader}
                            onHeaderClicked={this._onHeaderClicked}
                        />

**Comment by iRoachie** [comment]
Will look into this on the weekend

**Comment by alexstoyanov** [comment]
@iRoachie Did you have some time to look into this? 
It would be really helpful because if each section contains a lot of content and the user will not always open each section to see its content - it is unnecessary to retrieve the whole data from a server when rendering the screen.

**Comment by iRoachie** [comment]
Not as yet i’m afraid. Been pretty bogged down at work. Will try to block off Tuesday evening to look through the issues

**Comment by iRoachie** [comment]
Hey @alexstoyanov so I've got a solution that doesn't need to change anything in the api. You simply just have to put the `sections` array in your state, and then update in the `onChange` callback.

Here's an example video I made:

https://www.useloom.com/share/e97dde841afb404da3bda216d17becd1

**Comment by iRoachie** [comment]
Closing this as inactive. If the solution didn't work for you let me know.

**Comment by archvill** [comment]
I've had exactly the same requirement, child component should only fetch and render data if user expands an accordion. And also we'd like to force data reload every time user expands it again. The solution was simple - since that's our responsibility to maintain collapsed state, we've put children into the collapsible only it is expanded:

    const { collapsed } = this.state;
    ...
    <SomeHeaderComponent onPress={this.toggleCollapsed}/>
    <Collapsible collapsed={this.state.collapsed}>
    {!collapsed && <HeavyReportView/>}
    </Collapsible>

The single issue was when server response came faster than accordion stops animating, in that case, it simply stucks until child component got re-rendered.
Solution was to run a 300-ms promise (transition duration in our case) in parallel to fetch() request, and then waiting the one which will happen later with `Promise.all()`.

**Comment by jplandry908** [comment]
@iRoachie - I know this is an old post, but this worked great for me. Thank you!
