### ISSUE TITLE
Rerenders as many times as there are accordion cards.

### ISSUE THREAD

**Issue by nichesoftgh04** [oblador/react-native-collapsible#146]
When click on one card to expand it the whole list is rerendered as many times as there are accordion cards. Suppose i have 25 cards and i open one of them it will render 25 times on each click and it becomes very slow with very small amount of data(like 50 cards). It should render only one list which is requested by user click.

**Comment by iRoachie** [comment]
Hey could create a simple example of this behavior on https://snack.expo.io ?

**Comment by mgit7** [comment]
I am having the same problem.  Is there anyway we can have each collapsible 
 component render separately when clicked on instead of having all rerender?

**Comment by JoseVf** [comment]
https://snack.expo.io/ByBGJ18dz
If you add more sections it will show more dots each time you tap on a header.

**Comment by mgit7** [comment]
Did anyone figure out a way to fix this issue?  It really brings the performance down.

**Comment by iRoachie** [comment]
I don't have a way to easily fix this in the library itself. My first thought was to use `shouldComponentUpdate` in the Collapsible to only update if `props.collapsed` is different from the previous value. However since we use `componentWillReceiveProps` to calculate the measure then the above approach won't work.

My solution to you is to wrap your make your component in the `renderContent` a PureComponent or make your own wrapper that implements `shouldComponentUpdate`. That way the content will not be re-rendered.

**Comment by iRoachie** [comment]
Closing as inactive, if the above solution didn't work then comment here or create another issue with an example.
