### ISSUE TITLE
How to make collapse multiple ? herein example only single collapse

### ISSUE THREAD

**Issue by mthohir** [oblador/react-native-collapsible#163]

**Comment by iRoachie** [comment]
Could you be a bit clearer in your question?

**Comment by jdonald** [comment]
Pretty sure @mthohir is asking how to make more than one content row expanded at a time, because I'm looking to do the same thing.

Given the API has properties like activeSection but not activeSection**s** it does not look like `react-native-collapsible` is designed for this, but any advice if we were to try to hack in the capability locally?

**Comment by jdonald** [comment]
Answering my own question: I poked at the code and hammered something out that works for me: https://github.com/oblador/react-native-collapsible/compare/master...jdonald:multi-collapse-expand?expand=1

Would it be okay to remove (replace) the activeSection property?

**Comment by iRoachie** [comment]
Is there any reason you didn't use the Collapsible by itself then if you don't need the behavior of an Accordion? An Accordion is a specific behavior https://en.wikipedia.org/wiki/Accordion_(GUI).

If you want to have multiple sections open, then recommend you use collapsible, and loop over your items. That way you can have multiple sections open since you manage your own state.

**Comment by hanzou-x** [comment]
We could implement this from the ground up via Collapsible but I think that's basically reimplementing Accordion. It has its handy properties as well as functionality such as a distinct renderHeader and renderContent functions.

The second sentence on that Wikipedia link says:
> There can be zero expanded items, exactly one, *or more than one item expanded at a time*, depending on the configuration.

which suggests this particular feature request by @mthohir and myself is a reasonable enhancement to Accordion.

**Comment by jdonald** [comment]
We could implement this from the ground up via Collapsible but I think that's basically reimplementing Accordion. It has its handy properties as well as functionality such as a distinct renderHeader and renderContent functions.

The second sentence on that Wikipedia link says:
> There can be zero expanded items, exactly one, *or more than one item expanded at a time,* depending on the configuration.

which suggests this particular feature request by @mthohir and myself is a reasonable enhancement to Accordion.

**Comment by iRoachie** [comment]
Alright then, I suppose so! I'll add it for the next release.

**Comment by sabiya115** [comment]
@iRoachie Can you please add this feature ASAP, it's very much required.

**Comment by iRoachie** [comment]
I’ll try to look over the PR tonight

**Comment by NelGarbuzova** [comment]
Is this feature implemented now? Will be great to have some boolean flag for this.

**Comment by iRoachie** [comment]
Just released in [0.14](https://github.com/oblador/react-native-collapsible/releases/tag/v0.14.0). Be sure to check section on breaking changes. Thanks for being patient!

**Comment by iRoachie** [comment]
Updated my last comment! I had released it as 0.14.0 but was told that breaks semantic versioning. So I removed 0.14.0 and published it as 1.0.0
